- package.json
- src/invocationValidator.ts
- src/jira/fetchBatchOfIssues.ts
- src/jira/fetchBatchOfUsers.ts
- src/synchronizers/synchronizeAccountAndProjects.ts
The problem turned out to be that the customer had set the hostname to something totally invalid. The Jira client itself was hitting that and getting back junk data! :dizzy_face:
> Validate hostname and trace logs

- package.json
- src/executionHandler.test.ts
- src/initializeContext.test.ts
- src/initializeContext.ts
- src/jira/fetchBatchOfIssues.ts
- src/jira/fetchBatchOfUsers.ts
- src/synchronizers/synchronizeAccountAndProjects.ts
- src/synchronizers/synchronizeIssues.ts
- src/utils/getLastSyncTime.ts
- yarn.lock
Again, including @austin-rausch due to bump from `secretsmanager` pre-release.
> Upgrade SDK to 26.0.0

- src/jira/fetchBatchOfIssues.ts
- src/synchronizers/synchronizeIssues.ts
Also, temporarily disable `lastJobTimestamp` usage to get back full issue history (!)
> Only send create operations for issues

- src/converters/IssueEntityConverter.ts
Some of these fields were being checked and some weren't, for some reason. :man_shrugging:
> Handle missing issue fields

- package.json
- src/converters/AccountEntityConverter.ts
- src/converters/AccountProjectRelationshipConverter.ts
- src/converters/IssueEntityConverter.ts
- src/converters/IssueUserRelationshipConverter.ts
- src/converters/ProjectEntityConverter.ts
- src/converters/ProjectIssueRelationshipConverter.ts
- src/converters/UserEntityConverter.ts
- src/index.ts
- src/jira/fetchBatchOfIssues.ts
- src/jira/fetchBatchOfUsers.ts
- yarn.lock
It'll be easier to just release this than link it *and* the new version of the SDK.
> Upgrade to SDK v30.1.1

- src/converters/IssueEntityConverter.ts
- src/jira/types.ts
Wish we had Polly in here. Also, it's hard to test some changes to this integration as it will only get issues modified since last run.
> JPT-2512: Set resolution property to resolution object name

- jest.config.js
- package.json
- src/index.ts
- src/jira/JiraClient.ts
- test/fixtures/users-ok.json
- yarn.lock
Use the endpoint that does not require query parameters https://developer.atlassian.com/cloud/jira/platform/rest/v3/#api-rest-api-3-users-get to avoid a `400` response we have started seeing on the `/users/search` endpoint. We aren't searching, just listing all anyhow.
This API is documented at the Jira site, and exists in the `jira-client` library, but is not available in the `@types/jira-client` typings.
> Fix 400 response fetching users

- CHANGELOG.md
- package.json
- yarn.lock
> Release 2.3.4

- CHANGELOG.md
- docs/jupiterone.md
> updated docs

- CHANGELOG.md
- src/steps/issues.ts
Stop writing jira_issues to disk. It isn't necessary and disk usage can rapidly increase when performing bulk-ingestion.
API
relationships, and their property names, to ensure those questions still
function with my changes.
> [INT-4658] don't write jira_issues to disk

- CHANGELOG.md
- src/jira/__recordings__/withCustomPath_1423265377/recording.har
- src/jira/detectApiVersion.test.ts
- src/jira/detectApiVersion.ts
- src/jira/types.ts
This change fixes the previously encountered issue:
```[validation_failure] - Error occurred while validating integration configuration. (errorCode="UNKNOWN_JIRA_API_VERSION", errorId="...", reason="Could not detect the Jira server version (/rest/api/{3,2}/serverInfo):")```
API
[JupiterOne data …
> INT-5912 - Support a path in the hostname of the Jira Integration

- CHANGELOG.md
- package.json
- version 3.3.0
API
relationships, and their property names, …
> Version 3.3.0

- CHANGELOG.md
- src/converters/IssueEntityConverter.test.ts
- src/converters/IssueEntityConverter.ts
- src/jira/types.ts
- src/steps/__snapshots__/index.test.ts.snap
- src/steps/issues.ts
This supports ingestion of description fields from v2 issues.
API
reviewed all existing managed questions referencing the …
> INT-3567 - Support v2 description fields

- docs/jupiterone.md
> Updating nav instructions

- CHANGELOG.md
- package.json
> NO-TICKET -  v3.7.0

- .github/workflows/build.yml
- .gitignore
- CHANGELOG.md
- README.md
- build.sh
- package.json
- yarn.lock
Added the `auto` package to improve automation for builds, versioning and npm.
Modify package.json and 4 other project files to include the `auto` package dependency and build logic. 
- [x ] New feature (non-breaking change which adds functionality)
- [x ] I have performed a self-review of my own code
- [ x] New and existing unit tests pass locally with my changes
API
match the recommended model for this …
> INT-7808: add auto package

- src/actions.ts
Minor simplification to types.
Minor simplification to types, and re-release previous changes as a major version.
See: https://github.com/JupiterOne/graph-jira/pull/192
> [APP-12341] Build type synthetically rather than subtractively

- package.json
- src/config.ts
- src/constants.ts
- src/index.ts
- src/steps/issues.ts
- src/steps/projects.ts
- src/steps/users.ts
- yarn.lock
> Add Ingestion sources config

- src/jira/JiraClient.test.ts
- src/jira/JiraClient.ts
- src/jira/__recordings__/addNewIssue_4206205249/recording.har
Add logging for errors encountered when creating Jira issues.
Wraps the call to add a new issue in a try/catch and logs the error before throwing.
API
relationships, and their property names, to ensure those questions still
function with my changes.
> [APP-13581] log issue creation error

- .github/workflows/package-publish.yml
> Trying with new import

- .github/workflows/package-publish.yml
Reverts JupiterOne/graph-jira#203
> Revert "Trying with new import"

- .github/workflows/package-publish.yml
Triggers weren't right previously
> Actual workflow fix

- src/config.ts
Make the remaining fields that are optional actually optional in the config.
> MAke remaining fields optional

- src/converters/IssueEntityConverter.ts
- src/steps/issues.ts
Just adding some logs that could help us debug this kinds of situations.
API
reviewed all existing managed questions referencing …
> Added logs to understand behaviour

- package.json
Somehow we ended up on version 5.0.8 but package.json was outdated
API
reviewed all existing managed questions referencing the …
> Fixed package.json version

- src/steps/issues.ts
> Add log information

- src/converters/IssueEntityConverter.ts
- src/steps/issues.ts
Adding logs (will remove in an hour) to know what is going on for that specific field, why is it not working
API
reviewed all …
> Add logs for the specific ticket

- src/converters/IssueEntityConverter.ts
> Removed temp logs from integration

- .github/workflows/package-publish.yml
> Fix collector release workflow

- src/steps/issues.ts
> INT-10388: update max issues ingestion limit

- .env.example
- src/config.ts
- src/converters/IssueEntityConverter.ts
- src/steps/issues.ts
> added complex custom field property

- .env.example
- src/config.ts
- src/converters/IssueEntityConverter.ts
- src/steps/issues.ts
> resolved PR comments
